ui: mocha-bdd
scripts:
  - "lib/hoops.js"
concurrency: 1
browsers:
  - name: chrome
    version: latest
    platform: Linux
  - name: firefox
    version: latest
    platform: Linux
  - name: safari
    version: 7
  - name: ie
    version: 8..latest
